### ISSUE TITLE
Contents of Edit field do not appear

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ewc-client#105]
Run Demo_Issue105 and note that all the edit fields are blank, despite:

 30:05.497 T:  #10: {"WS":{"ID":"F1.∆pP1.B31003","Properties":{"Text":"WS1"}}} 
 30:05.499 T:  #10: {"WS":{"ID":"F1.∆pP1.B31002","Properties":{"Text":"SUPER"}}} 

Also note that the Password field "F1.∆pP1.B31001" does not display a "*".

**Comment by mbaas2** [comment]
The password field is still showing the value that is entered - the html input control should be of type `password`.

**Comment by mbaas2** [comment]
I don't know if we had a regression or if the issue was closed prematurely - but the password field still has a problem: it shows no value at all.  As I wrote above:  the html input control should be of type password.

**Comment by mkromberg** [comment]
No password is displayed because the code does not set one. I have updated Demo_Issue105.
