### ISSUE TITLE
Multi-point text does not appear (originally: Form is not drawn until Size is set)

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ewc-client#116]
Run Demo_Issue116. Nothing appears. Run Demo_Issue116p, which is identical except that it adds one message after the WS of the BCol:

{"WS":{"ID":"F1","Properties":{"Size":[95,745]}}} 

... now the form appears.

**Comment by mkromberg** [comment]
After the original problem was solved, it is still a problem that the text does not appear on the form.

**Comment by mbaas2** [comment]
There seems to be some sort of regression, as Demo_Issue116 and Demo_Issue116p both just produce an empty screen.
![grafik](https://github.com/user-attachments/assets/189279bd-4da6-43c7-9df3-a964efccfc01)

**Comment by mkromberg** [comment]
I suspect that a fix that allowed a multi-line text to be displayed using a single co-ordinate has broken this case, where a three-element text has three distinct points.

The problematic text property is created using:
{"WC":{"ID":"F1.TEXT1","Properties":{"HAlign":1,"Points":[[[10,25,40],[190,190,190]]],"Text":["                   ","Operation Cancelled","                   "],"Type":"Text"}}}
