### ISSUE TITLE
The id attribute of 'label' controls is not shown in Html

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ewc-client#136]
Open the demo app and look it with devtools.
![grafik](https://github.com/mqasim23/jswc-web/assets/5645494/dc9afb11-2c43-4d29-a182-fcb00aff711d)

This label is created with 
````
 'F1.L1' eWC 'Label' ('Welcome to EWC, Session #',⍕_JSWC.ID) (6 5)('Size' (23 200))
````
and the corresponding Html is
````
<div style="position: absolute; height: 23px; width: 200px; top: 6px; left: 5px; font-size: 11px; text-decoration: none; display: block;">Welcome to EWC, Session #1</div>
````
---> it does not show the id!

(@mkromberg I'm not sure abt the workflow. Maybe it's best if I assign these issues to you 1st so that you cen review them and dedice about priority and label and then assign it to @mqasim23 ?)

**Comment by mkromberg** [comment]
Thanks Michael! I am going to give all these new test failures priority 1. They are not blocking my work on the client application, but they are important.
