### ISSUE TITLE
The div created for a poly control should have the id given to the poly

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ewc-client#153]
see DemoBoxes

**NB**: this was logged against the current version of the `grid/cell-move` branch.

**Comment by mbaas2** [comment]
Morten said this should be solved in  branch "refactor/grid", but I can't find `F1.LOGO` in the Html!

**Comment by mqasim23** [comment]
Can you please tell me the Demo name in which you are looking for the id's? @mbaas2

**Comment by mbaas2** [comment]
Yeah, looks good! 👍
