### ISSUE TITLE
DemoEdit: when editing the 2nd date (11-04-2024), the default value in the popup selector is 10-04-2024.

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ewc-client#156]
It works ok for the first row, but the 2nd value is off by 1 (at least until it is edited). Probably it always uses "today" as default?

**NB**: this was logged against the current version of the `grid/cell-move` branch.

**Comment by mqasim23** [comment]
please verify this on "staging" branch

**Comment by mbaas2** [comment]
fixed
