### ISSUE TITLE
DemoFonts / Fontsizes

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ewc-client#170]
There is a difference between "advertised" and real font-sizes:
![image](https://github.com/mqasim23/jswc-web/assets/5645494/94a39cc6-9160-4047-bb35-5fd572cd6371)

I'm not sure if I have forgotten about a plausible explanation or if there is none - can you please help me? 😉

BTW: I checked window.devicePixelRatio in the browser and it is =1.

**Comment by mqasim23** [comment]
Sure, I will give you an explanation but I need more context about the issue like How can I reproduce the Issue on my side?

**Comment by mbaas2** [comment]
Just run Morten's DemoFonts. It creates Font objects and creates labels (using those font objects)  which print the size of the coresponding objects. The screenshot above was taken from a `div` that corresponds to such a label.

**Comment by mqasim23** [comment]
You can ask Morten about that because I receive this information for that label
 {"WC":{"ID":"F1.FNT2304","Properties":{"Italic":1,"PName":"Arial","Size":17,"Type":"Font","Underline":0,"Weight":700}}}

**Comment by mbaas2** [comment]
You're right. You're showing an unrelated definition in your reply, here are the correct details (and it looks indeed like an error in @mkromberg's code (Morten is in meetings - I'll have a look):

That label is defined as
`{"WC":{"ID":"F1.FNT2301LBL","Properties":{"Caption":"20px BI","FontObj":"F1.FNT2301","Posn":[645,40],"Type":"Label"}}}`

and the associated FontObj was defined as
`{"WC":{"ID":"F1.FNT2301","Properties":{"Italic":1,"PName":"Segoe UI","Size":17,"Type":"Font","Underline":0,"Weight":700}}}`

**Comment by mbaas2** [comment]
Ok, it's not a bug - it's by design:  Function `fixUpProps` did this:
`(ix⊃values)←⌊0.5+0.85×ix⊃values ⍝ Adjust font size down`

**Comment by mbaas2** [comment]
I#ll leave this issue open, so @mkromberg can decide if he wants to do anything or not.

**Comment by mkromberg** [comment]
My conclusion is that this was a mistake early on in the project, I have removed it.
