### ISSUE TITLE
Text objects created by demo "TextSize" are not shown on the page

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ewc-client#173]
The demo TextSize creates a text object `F1.HW` that contains a matrix: 1st row containing test "Hello to" - this one is shown, and a 2nd row containing "all of the world" - this text is not visible on the page or in the html.

Also, my favorite issue applies here as well (#157: missing ids! ) because the objects that are created for those Text objects do not have an id...

**Comment by mqasim23** [comment]
![image](https://github.com/mqasim23/jswc-web/assets/138499482/23b0e798-0c21-4016-a93c-7e808d75804b)

**Comment by mbaas2** [comment]
Is that screenshot after you fixed it? (I did not see that 2nd line)

**Comment by mqasim23** [comment]
I have updated the main branch. Please try with the main branch

**Comment by mbaas2** [comment]
Yup, the text is there now!👍
But the text objects `F1.H` and `F1.HW`still don not have an id!

**Comment by mbaas2** [comment]
I tested against [e09c879](https://github.com/mqasim23/jswc-web/commit/e09c879b612f710e82223c9a474b202cc17f80ff)
 and the ids are ok now - but there's been a regression with regards to the positioning of the text:
![grafik](https://github.com/mqasim23/jswc-web/assets/5645494/dc4cc2c0-c544-4fca-9f53-67e3f44bfe6f)

**Comment by mbaas2** [comment]
I tested against [e09c879](https://github.com/mqasim23/jswc-web/commit/e09c879b612f710e82223c9a474b202cc17f80ff)
 and the ids are ok now - but there's been a regression with regards to the positioning of the text:
![grafik](https://github.com/mqasim23/jswc-web/assets/5645494/eaa5bfdf-131d-4e0b-9024-e13185478b78)
