### ISSUE TITLE
DatePicker popup (in DemoEdit) initialized with wrong date

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ewc-client#176]
The 3d column of the 2nd line in DemoEdit shows yesterday's date. If you open the DatePicker for that date. it shows t-1 as default. (This only happens in the 2nd row - 1st row is correct.

Also: is there a way to manually enter a date in the edit cells? (In ⎕W, this is possible)

**Comment by mqasim23** [comment]
please verify this on "staging" branch

**Comment by mqasim23** [comment]
Also for manual date entry, can you please another ticket

**Comment by mbaas2** [comment]
fixed in "staging"👍
