### ISSUE TITLE
Text is incorrectly displayed in DemoLines

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ewc-client#179]
There should only be one line of text at each Point. This was working earlier.

{"WC":{"ID":"F1.T1","Properties":{"FCol":[[255,0,0],[0,255,0],[0,0,255]],"Points":[[120,140,160],[20,30,40]],"Text":["RED","GREEN","BLUE"],"Type":"Text"}}}

![image](https://github.com/mqasim23/jswc-web/assets/2799045/b8b8665d-b023-4e5b-aded-4a8ad040cdaa)

**Comment by mbaas2** [comment]
Please also do not forget to add IDs to the `tspan`objects! 😉

**Comment by mkromberg** [comment]
Note that this also happens in DemoFonts - the column headers are repeated.
