### ISSUE TITLE
TabButtons do not have an id - it should match the one that's used with the WC-message

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ewc-client#183]
see DemoRibbonTab2:  the divs corresponding to the  3 tab buttons `F1.TC.T1..3` do not have ids.

**Comment by mqasim23** [comment]
please verify this on "staging" branch

**Comment by mbaas2** [comment]
Thanks - this is beginning to work. But the current implementation creates duplicate ids when a ButtonGroup contains multiple elements (for example Application > Shares: "Denmark" and "Blue" both get id="F1.TC.SF3.Ribbon.Item4.GroupItem1.ButtonGroup1"

**Comment by mqasim23** [comment]
Can you kindly verify now in staging branch, unique ids will be generated in buttonGroup

**Comment by mbaas2** [comment]
Thanks - it works! 👍
