### ISSUE TITLE
Grids border width changes as cursor moves in the grid

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ewc-client#187]
When the cursor moves in the grid (by clicking cells or using keypresses), the width of the grid's border changes: (DemoGrids)
![grafik](https://github.com/mqasim23/jswc-web/assets/5645494/10edce04-bc70-460a-befd-79bd9d267af7)
![grafik](https://github.com/mqasim23/jswc-web/assets/5645494/f15a8b68-d36f-4a71-9596-f30f8588efed)

**Comment by mbaas2** [comment]
I'm looking at the "main" branch and can still repro:

- load DemoGrids
- click into cell [2;5] (value 6,301)
- press cursor left

I happened immediately when I tested in mode 0 (=desktop), with the browser it needed some more movement using the keyboard.

**Comment by mqasim23** [comment]
Hey please verify this issue in staging branch
