### ISSUE TITLE
Grid cells need to be formatted when leaving the cell  after edit

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ewc-client#191]
- load DemoGrids
- dbc-click in row "ABCD", colum "Value", Value="6,301"
- the cell shows it's current value "6301.29" for editing
- click into another cell - the cell's content does not change. It should be reformatted when the cells loses focus

**Comment by mqasim23** [comment]
please verify this on "staging" branch

**Comment by mbaas2** [comment]
✅looks good
