### ISSUE TITLE
enable manual input in date fields

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ewc-client#195]
Example: DemoEdit, 1st grid has a "Birthday" column: it should be possible to manually enter a date into these fields.

Please note that manual input needs to be validated! The details (ie. Events to be trriggered on invalid input etc.) are documented @ https://help.dyalog.com/19.0/Content/GUI/Objects/Edit.htm

**Comment by mqasim23** [comment]
Kindly verify in staging, When a cell is double-clicked, it becomes editable. To support manual date entry, I have added a date picker button next to the input field. This button would appear when the cell is double-clicked, allowing manual date entry while also providing a date picker.

**Comment by mbaas2** [comment]
yep, it works👍
