### ISSUE TITLE
Client responds to CellMove message with wrong co-ordinates

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ewc-client#210]
Run DemoScroll. Click in cell [1,3] and press the "Page Down" key. Notice:

Server sends a CellMove to the last row of the grid:
{"NQ":{"Event":"CellMove","ID":"F1.VGRID","Info":[10,1,1],"NoCallback":0}} 

Server sends EC message to signal that it has finished processing the KeyPress Event
{"EC":{"EventID":"e5deca30-ff5a-4fe7-9bce-cedf972d46b6","Proceed":1}} 

Client responds with CellMove Event to [12,1], this should of course be [10,1]
{"Event":{"ID":"F1.VGRID","EventName":"CellMove","Info":[12,1,0,0,0,0,""]}}

**Comment by mbaas2** [comment]
Also it doesn't always send the CellMove event.

Repro using DemoEdit:
- click into the cell for Amir/Score: APL session shows event `CellMove`
- click the cell `Amir`/`Name`: no update!
- click `Amir`/`Gender`: no update!
- click `Birthday`: APL Session shows event `CellMove` (also `Score `and `Expert `are working)
- the problem only occurs when you use the mouse to navigate, keyboard nav seems to always trigger the event
