### ISSUE TITLE
Scroll object fixes required

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ewc-client#272]
Run Demo_Issue272

1) If Thumb is not set, WG of 'Thumb' does not respond.
2) If no Size is set, the Size should default to 17 pixels wide - currently it defaults to filling the entire contained with the scroll bar.
3) No arrowheads are drawn - I am sure they were there before?

![image](https://github.com/user-attachments/assets/e63ddf50-1f4d-4afd-a97d-20ae9813cba2)

**Comment by cursork** [comment]
Demo: https://github.com/Dyalog/ewc/compare/issue272

**Comment by cursork** [comment]
https://github.com/Dyalog/ewc-client/pull/283

I believe these were fixed by that change.
