### ISSUE TITLE
Upload fails if file is selected, but updated before upload

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ewc-client#274]
Running DemoUploadDownload: If a file is selected for upload, and updated before the upload button is clicked, request for content fails:

26:45.479 W:  Request was: {"WG":{"ID":"F1.UPLOAD","Properties":["FileBytes"],"WGID":"10"}} 
12:VALUE ERROR
CBUpload[7] b64←'F1.UPLOAD'eWG'FileBytes'
                              ∧

(tested using Excel and an .xlsx file)

**Comment by cursork** [comment]
This was resolved.
