### ISSUE TITLE
DemoTextSize is broken - again

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ewc-client#301]
DemoTextSize has been updated to test more texts, and no longer draw boxes.

The boxes should all touch the extreme bottom and right of the text. Below:

- The first one has too much space below
- The second has the y descending outside the box
- The third has the text "   " (three blanks) but the client returns a size of [-11,0]
- The fourth has a box which is not deep enough.

![image](https://github.com/user-attachments/assets/1dd3a6fb-7770-4bf0-8727-340a617d15ec)

**Comment by cursork** [comment]
Mostly fixed in branch next, but with maybe a pixel out here or there.
