### ISSUE TITLE
No space between menu items

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/ewc-client#4]
Top level menus are not separated by a space. To reproduce, select demo "Original". Notice there is no space between that "File" and "Colours".
![image](https://github.com/mqasim23/jswc-web/assets/2799045/70df316a-a768-4a9c-8407-9d10e0dcaaa1)

**Comment by mqasim23** [comment]
![image](https://github.com/mqasim23/jswc-web/assets/138499482/3846b3aa-ebaf-49a9-8e04-0ee1a2e8a0ca)
I didn't reproduce the issue on my side
